### PR TITLE
fix hashes for iperf-2.0.9.tar.gz 

### PR DESCRIPTION
**Pull request by citronalco**
See https://sourceforge.net/p/iperf2/tickets/20/

### CODE REVIEW

**Comment by rickgaiser** [comment]
Upstream buildroot has already fixed this, so I think it's better to cherry-pick from there:
https://github.com/buildroot/buildroot/commit/bb0d5044be8b7d9adc935aea22c4fdc2ac3efe1e#diff-0d35e7b09029d2f8d49f31f651fda9b9

But why not pull all fixes from the 2017.02.x branch:
https://github.com/rickgaiser/buildroot/compare/ps2-2017.02...buildroot:2017.02.x

If we want to keep moving forward with linux on the ps2, then it's probably best to rebase our ps2 changes onto 2018.08.x (https://github.com/buildroot/buildroot/tree/2018.08.x) and into a new branch. But that's a little more.

What do you think?

**Comment by citronalco** [comment]
That's way beyond my knowledge - I'm pretty happy I got the whole thing working somehow. Sorry.

**Comment by rickgaiser** [comment]
I'll look into this when I get the time. Thank you for investigating.

**Comment by rickgaiser** [comment]
I've pulled in all fixes from the 2017.02.x branch. This and many other problems should now be fixed.

**Pull request closed without merging**
